### ISSUE TITLE
Feature request: Show more coverage metrics between Echidna iterations

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/optik#80]
If we check the diff between each coverage file generated by Echidna (coverage.*.txt), we can see an approximation of how many new lines are covered between iterations. Showing that number is useful to know that the tool is helping to produce new coverage.

**Comment by Boyan-MILANOV** [comment]
Should we show only the number of new lines reached by the last iteration, or also the total number of new lines covered since the first iteration? The former is a better indicator of current progress while the latter is an indicator of how much symbolic execution has helped across all iterations.

I also point out that this type of metric can be tricky, because sometimes a single line of code translations into multiple branches in the bytecode. For instance `if (x == 1 && y == 2 && z ==3 )` will result in 3 different tests in the bytecode, and thus likely require multiple iterations to be solved thoroughly. So the "number of new lines reached by the last iteration" will be zero when we solve `x == 1` and `y == 2`, which could be misinterpreted as Optik not making progress anymore even though it actually does...

**Comment by ggrieco-tob** [comment]
The metric is trick and should be carefully interpreted taking a look to the code, nevertheless is useful, in both form either as new lines from the last iteration and new lines discovered in total. The documentation should warn the user that it is an approximation and we should still show the new cases that the symbolic analyzer founds and the ones that fuzzing found.

**Comment by Boyan-MILANOV** [comment]
@ggrieco-tob: I'm working on this. I'm thinking about displaying instruction coverage instead of source code (lines) coverage. The reason is that instruction coverage is a more accurate metric of actual progress.

Are you fine with instruction coverage info, or do you think source code (lines) coverage is better? It's also possible to add both, but it sounds kind of redundant and I don't want to overload the UI.

**Comment by ggrieco-tob** [comment]
optik is in a experimental stage and we can take some risk here. So let's experiment with different UIs and made changes, since they will impact a very small number of users.

**Comment by Boyan-MILANOV** [comment]
@ggrieco-tob what do you think about this? It shows both line and instruction coverage

![Screenshot 2022-09-01 at 17 48 22](https://user-images.githubusercontent.com/16084180/187957597-4233bc8c-d25e-4c95-b054-d4047e2ed33d.png)
